app:
  name: "runner-manager-backend"
  version: "v0.0.1"
  scheme: "http"
  host: "localhost:3002"
  environment: development #local,development,staging,production

server:
  hosr: "0.0.0.0"
  port: "9090"
  debug: true
  timezone: "Ukraine/Kyiv"


database:
  host: 127.0.0.1
  port: 3306
  name: users
  user: root
  password: pwd

authentication:
  key: example
  sign: example
